apiVersion: v1
kind: Service
metadata:
  namespace: internal-tools
  name: kuma-svc
spec:
  selector:
    name: kuma-dpl
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3001
      nodePort: 32081
  type: LoadBalancer
  loadBalancerIP: 192.168.3.214
