- name: INSTALLING K3S - MASTER
  hosts: MASTER
  tasks:
    - name: -> MASTER - INSTALL K3S
      shell: |
        curl -sfL https://get.k3s.io | sh -s - \
        --write-kubeconfig-mode 644 \
        --disable servicelb,traefik,metrics-server \
        --token master-password \
        --node-taint CriticalAddonsOnly=true:NoExecute \
        --bind-address 192.168.3.102 \
        --node-name MASTER
      become: yes
      become_user: root
      register: k3s_install
      ignore_errors: no

    - name: -> MASTER - GET TOKEN
      shell: |
        cat /etc/rancher/k3s/k3s.yaml
      become: yes
      become_user: root
      register: k3s_token
      ignore_errors: no

    - name: -> MASTER - SAVE TOKEN
      delegate_to: localhost
      copy:
        content: "{{ k3s_token.stdout }}"
        dest: /Users/nicolas.mmb/.kube/token.yaml
      ignore_errors: no
    
- name: NODES - INSTALLING K3S
  hosts: NODES
  tasks:
    - name: -> NODE - INSTALL K3S
      shell: |
        curl -sfL https://get.k3s.io | \
        K3S_URL=https://192.168.3.102:6443 \
        K3S_TOKEN=master-password \
        K3S_NODE_NAME=NODE-{{inventory_hostname.upper()}} \
        sh -

# ansible-playbook -i hosts.yaml playbook.yaml 