# expose kubernetes dashboard
apiVersion: v1
kind: Service
metadata:
  name: kubernetes-dashboard
  namespace: kubernetes-dashboard

spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8443
      protocol: TCP
  selector:
    name: kubernetes-dashboard

# expose metallb
---
apiVersion: v1
kind: Service
metadata:
  name: metallb
  namespace: metallb-system
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 7472
      protocol: TCP
  selector:
    app: metallb

# expose nginx-ingress
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-ingress
  # namespace: nginx-ingress
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: nginx-ingress
