apiVersion: v1
kind: Namespace
metadata:
  name: cloudflare-servers
  labels:
    name: cloudflare-servers

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflare-pihole-dpl
  namespace: cloudflare-servers
  labels:
    app: pihole
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pihole
  template:
    metadata:
      labels:
        app: pihole
    spec:
      containers:
        - name: cloudflare
          image: cloudflare/cloudflared:latest
          imagePullPolicy: Always
          resources:
            requests:
              memory: "128Mi"
              cpu: "64m"
            limits:
              memory: "256Mi"
              cpu: "128m"
          args:
            - "tunnel"
            - "--no-autoupdate"
            - "run"
            - "--token"
            - "<CLOUDFLARE-TUNEL-TOKEN>"

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: cloudflare-pihole-hpa
  namespace: cloudflare-servers
  labels:
    app: pihole
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cloudflare-pihole-dpl
  minReplicas: 1
  maxReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 90
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 90
  behavior:
    scaleDown:
      policies:
        - type: Pods
          value: 1
          periodSeconds: 30
    scaleUp:
      policies:
        - type: Pods
          value: 1
          periodSeconds: 30
