kind: PersistentVolume
apiVersion: v1
metadata:
  namespace: internal-tools
  name: pihole-pv
spec:
  capacity:
    storage: 256Mi
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  storageClassName: manual
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/data/internal-tools-pihole"

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: internal-tools
  name: pihole-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 256Mi
