apiVersion: v1
kind: Service
metadata:
  namespace: internal-tools
  name: pihole-svc
spec:
  selector:
    name: pihole-dpl
  ports:
    - name: dns-udp
      protocol: UDP
      port: 53
      nodePort: 31053
    - name: dns-tcp
      protocol: TCP
      port: 53
      nodePort: 31053
    - name: http
      protocol: TCP
      port: 80
      nodePort: 31080
    - name: https
      protocol: TCP
      port: 443
      nodePort: 31443
  type: LoadBalancer
  loadBalancerIP: 192.168.3.215
