kind: Pod
apiVersion: v1
metadata:
  namespace: internal-tools
  name: pihole-pod
  labels:
    app: pihole
spec:
  containers:
    - name: pihole
      image: pihole/pihole:latest
      resources:
        requests:
          memory: "128Mi"
          cpu: "64m"
        limits:
          memory: "200Mi"
          cpu: "250m"
      volumeMounts:
        - name: pihole-pv-claim
          mountPath: /etc/pihole
      env:
        - name: TZ
          value: "America/Sao_Paulo"
        - name: ServerIP
          value: "192.168.3.215"
        - name: DNS1
          value: "1.1.1.1"
        - name: DNS2
          value: "8.8.8.8"
        - name: "WEBPASSWORD"
          value: "admin"
      ports:
        - containerPort: 53
          name: dns-udp
          protocol: UDP
          hostPort: 53
        - containerPort: 53
          name: dns-tcp
          protocol: TCP
          hostPort: 53
        - containerPort: 80
          name: http
          protocol: TCP
          hostPort: 8001
        - containerPort: 443
          name: https
          protocol: TCP
          hostPort: 443
  volumes:
    - name: pihole-pv-claim
      persistentVolumeClaim:
        claimName: pihole-pv-claim

  terminationGracePeriodSeconds: 10
  restartPolicy: Always
